I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 6, in script
    define d = character("Donna")
  File "game/script.rpy", line 6, in <module>
    define d = character("Donna")
NameError: name 'character' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 6, in script
    define d = character("Donna")
  File "/Users/sethwang/Desktop/renpy-7.4.2-sdk/renpy/ast.py", line 2235, in execute
    self.set()
  File "/Users/sethwang/Desktop/renpy-7.4.2-sdk/renpy/ast.py", line 2249, in set
    value = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "/Users/sethwang/Desktop/renpy-7.4.2-sdk/renpy/python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 6, in <module>
    define d = character("Donna")
NameError: name 'character' is not defined

macOS-10.16-x86_64-i386-64bit x86_64
Ren'Py 8.3.2.24090902
Reloaded_Gaming_Girls 1.0
Mon Nov 11 22:11:17 2024
