I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/options.rpy", line 21, in script
    define gui.show_name = false
  File "game/options.rpy", line 21, in <module>
    define gui.show_name = false
NameError: name 'false' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/options.rpy", line 21, in script
    define gui.show_name = false
  File "/Users/sethwang/Desktop/renpy-7.4.2-sdk/renpy/ast.py", line 2235, in execute
    self.set()
  File "/Users/sethwang/Desktop/renpy-7.4.2-sdk/renpy/ast.py", line 2249, in set
    value = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "/Users/sethwang/Desktop/renpy-7.4.2-sdk/renpy/python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/options.rpy", line 21, in <module>
    define gui.show_name = false
NameError: name 'false' is not defined

macOS-10.16-x86_64-i386-64bit x86_64
Ren'Py 8.3.2.24090902
Reloaded_Gaming_Girls 1.0
Sat Nov 23 21:55:01 2024
